	.OPT NO LIST
;PARTES DEL ORGANIZADOR
;
;PANTALLA DE INICIO COMO PRESENTACION
;PANTALLA DE MENU PRINCIPAL
;PANTALLA DE INGRESO
;PANTALLA DE VISTA DE DATOS
;PANTALLA DE DIRECTORIO
;PANTALLA DE INFORMACION DEL SISTEMA
;16KB PARA EL CODIGO
;32KB PARA EL INGRESO DE DATOS EN MEMORIA
;VARIOS ARCHIVOS QUE SE ADJUNTAN AL PRINCIPAL
	*=$2000
	.INCLUDE #PANTALLAS.ASM
;	.INCLUDE #D:PANTALLA.ASM PARA MAC65
CONSOLA = 53279
;WILLYSOFT(Guillermo Fuenzalida)
START
	LDA CONSOLA
	CMP #6
	BNE START
ESSTART
	LDA CONSOLA
	CMP #6
	BEQ ESSTART
FINSTART
	RTS
ESGET
	JSR $F2F8	;$F42A TODA UNA LINEA DE CARACTERES Y ESPERA UN RETURN
	RTS
INICIO
	LDA #$92
	STA 712
	LDA #0
	STA 710
	JSR PRINCIPAL
	JSR START
	LDA #$92
	STA 710
	LDA #0
	STA 712
MENUOPCION
	JSR MENUPRINCIPAL
	JSR ESGET
	CMP #78
	BEQ NUEVOARTICULO
	CMP #27
	BEQ ESESC
NUEVOARTICULO
	LDA #80
	STA 710
	JMP LOOP
ESESC
	LDA #25
	STA 712
LOOP
	JMP LOOP
	*=$2E0
	.WORD INICIO