	.OPT NO LIST
;PARTES DEL ORGANIZADOR
;
;PANTALLA DE INICIO COMO PRESENTACION
;PANTALLA DE MENU PRINCIPAL
;PANTALLA DE INGRESO
;PANTALLA DE VISTA DE DATOS
;PANTALLA DE DIRECTORIO
;PANTALLA DE INFORMACION DEL SISTEMA
;16KB PARA EL CODIGO
;32KB PARA EL INGRESO DE DATOS EN MEMORIA
;VARIOS ARCHIVOS QUE SE ADJUNTAN AL PRINCIPAL
	*=$2000
	.INCLUDE #PANTALLAS.ASM
;	.INCLUDE #D:PANTALLA.ASM PARA MAC65
INICIO
	LDA #$92
	STA 712
	LDA #0
	STA 710
	JSR PRINCIPAL
	LDA #14
	STA 709
LOOP
	JMP LOOP
	*=$2E0
	.WORD INICIO