	*=$2000
;ESTRUCTURA DISPLAY LIST
PORTADADLI
	.BYTE $70,$70,$70,$46
	.WORD LINEA01
	.BYTE $70,$70,$70,$47
	.WORD LINEA02
	.BYTE $70,$70,$70,$42
	.WORD LINEA03
	.BYTE $70,$70,$42
	.WORD LINEA04
	.BYTE $70,$70,$46
	.WORD LINEA05
	.BYTE $41
	.WORD PORTADADLI
;CARGA DE DATOS DEL DISPLAY LIST
PORTADA
	LDA #<PORTADADLI
	STA $230
	LDA #>PORTADADLI
	STA $231
	RTS
;DATA DISPLAY LIST
LINEA01
	;      "                    "
	.SBYTE "     HOLA MUNDO     "
LINEA02
	.SBYTE "  curso  assembler  "
LINEA03
	;      "                                        "
	.SBYTE "CURSO BASICO PARA PROGRAMADORES ASSEMBLE"
LINEA04
	.SBYTE "PARA TODOS LOS SEGUIDORES DE ESTE CURSO."
LINEA05
	.SBYTE "   QUEDO  BONITO   "
INICIO
	LDA #0
	STA 710
	JSR PORTADA
LOOP
	JMP LOOP
	*=$2E0
	.WORD INICIO