	*=$2000
VALIDACION?
	CLC
	LDA VARIABLE
	ADC #1
	STA VARIABLE
	CMP #1  
	BEQ ESPRIMERO
	CMP #2
	BEQ ESSEGUNDO
	CMP #3
	BEQ ESTERCERO
	CMP #0
	BEQ NOESNINGUNO
	CMP #4
	BCS TERMINO
ESPRIMERO
	LDX #<PRIMEROB
	LDY #>PRIMEROB
	JSR $C642
	JMP VALIDACION?
ESSEGUNDO
	LDX #<SEGUNDOB
	LDY #>SEGUNDOB
	JSR $C642
	JMP VALIDACION?
ESTERCERO
	LDX #<TERCEROB
	LDY #>TERCEROB
	JSR $C642
	JMP VALIDACION?
NOESNINGUNO
	LDX #<NOESNINGUNOB
	LDY #>NOESNINGUNOB
	JSR $C642
	JMP VALIDACION?
TERMINO
	RTS
INICIO
	LDA #0
	STA 710
	JSR VALIDACION?	;QUE ESPERA UN RETURN PARA VOLVER ACA(GOSUB)
;DESPUES DEL RETURN VUELVE ACA
LOOP
	JMP LOOP
PRIMEROB
	.BYTE "PRIMERA LINEA",$9B
SEGUNDOB
	.BYTE "SEGUNDA LINEA",$9B
TERCEROB
	.BYTE "TERCERA LINEA",$9B
NOESNINGUNOB
	.BYTE "NO ES NINGUNO",$9B
VARIABLE
	.BYTE 0
	*=$2E0
	.WORD INICIO